server:
  port: ${env.PORT}
---
spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:${env.KAFKA_HOST}}:${KAFKA_PORT:${env.KAFKA_PORT}}
    consumer:
      group-id: "my-awesome-app"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DB_URL:${env.DB_URL}}
    username: ${DB_USERNAME:${env.DB_USERNAME}}
    password: ${DB_PASSWORD:${env.DB_PASSWORD}}
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
  cache:
    type: redis
    redis:
      time-to-live: 300000
  data:
    redis:
      host: ${REDIS_HOST:${env.REDIS_HOST}}
      port: ${REDIS_PORT:${env.REDIS_PORT}}

---
app:
  token:
    secret: ${TOKEN_SECRET:${env.TOKEN_SECRET}}
    issuer: ${TOKEN_SECRET:${env.TOKEN_ISSUER}}
