server:
  port: 8080
---
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: "my-awesome-app"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${env.DB_URL}
    username: ${env.DB_USERNAME}
    password: ${env.DB_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
  cache:
    type: redis
    redis:
      time-to-live: 300000
  data:
    redis:
      host: localhost
      port: 6379

---
app:
  token:
    secret: ${env.TOKEN_SECRET}
    issuer: ${env.TOKEN_ISSUER}
